identidock:
  build: .
  ports:
    - "5000:5000"
  environment:
    ENV: DEV
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis

redis:
  image: redis:3.0

dnmonster:
  image: amouat/dnmonster:1.0
